'use strict';
angular.module("HM_GlobalMD",[
  'HM_DashboardMD',
  'HM_InvoicesMD',
  'HM_EnvMD',
  'HM_RoutesMD',
  'HM_ManageJobSitesMD',
  'HM_EquipmentDetailMD',
  'HM_EquipmentSellMD',
  'HM_EquipmentReserveMD',
  'HM_EquipmentReserveSuccessMD',
  'HM_LoginMD',
  'HM_ForgotPasswordMD',
  'HM_PortalAccessMD',
  'HM_UserProfileMD',
  'HM_LoadIndicatorMD',
  'HM_ManageMyAccountMD',
  'HM_MyCatalogueMD',
  'HM_QuotaNReservationsMD',
  'HM_TermsAndConditionsMD',
  'HM_MenuAimMD',
  'HM_RequestCallbackMD',
  'HM_LogoutMD',
  'HM_LandingMD',
  'HM_OrderHistoryMD',
  'HM_SearchMD',
  'HM_ActivateUserMD'

]);
